"""empty message

Revision ID: 7b0c60f1505f
Revises: 2e343eadcbb1
Create Date: 2021-06-20 18:48:11.589712

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7b0c60f1505f'
down_revision = '2e343eadcbb1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Artist', 'genres')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('genres', postgresql.ARRAY(sa.VARCHAR(length=50)), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
