"""empty message

Revision ID: 912390d72f26
Revises: 6361cbce6ab2
Create Date: 2021-06-20 13:44:35.224796

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '912390d72f26'
down_revision = '6361cbce6ab2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('website', sa.String(), nullable=True))
    op.add_column('Artist', sa.Column('seeking_venue', sa.Boolean(), nullable=True))
    op.add_column('Artist', sa.Column('seeking_description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Artist', 'seeking_description')
    op.drop_column('Artist', 'seeking_venue')
    op.drop_column('Artist', 'website')
    # ### end Alembic commands ###
